apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: httpd-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        resources:
          limits:
            cpu: 200m
            memory: "105Mi"
~                              
